steps:
- name: maven:3.8.7-eclipse-temurin-19
  entrypoint: mvn
  args: ['clean', 'test', '-f', './catalog/']
- name: maven:3.8.7-eclipse-temurin-19
  entrypoint: mvn
  args: ['clean', 'test', '-f', './frontend/']
- name: maven:3.8.7-eclipse-temurin-19
  entrypoint: mvn
  args: ['clean', 'test', '-f', './orders/']
- name: maven:3.8.7-eclipse-temurin-19
  entrypoint: mvn
  args: ['clean', 'test', '-f', './payment-history/']
- name: maven:3.8.7-eclipse-temurin-19
  entrypoint: mvn
  args: ['clean', 'test', '-f', './payments/']
options:
  env: ['STRIPE_API_KEY=sk_test_51Hjqs3AWdvlSRNTQmMxVBsFMK1nV09PEOpyVa2nMX3IX4RYe3bed3v2H7vqufHJvlSAEg17yzYB9liBOKBV3uEpq00xe7fzN4x']