apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: shopping-cart
  labels:
    app: catalog
    service: catalog
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: catalog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: shopping-cart
  labels:
    app: catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: ghcr.io/btjimerson/catalog
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: yugabyte
        - name: YB_URL
          value: "jdbc:yugabytedb://yb-tservers.yb-universes.svc.cluster.local:5433/yugabyte?sslmode=require"
        - name: YB_USER
          value: "yugabyte"
        - name: YB_PASSWORD
          value: "Password@11"
