---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: shopping-cart
  labels:
    app: payments
    service: payments
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: payments
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: shopping-cart
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      serviceAccount: payment
      containers:
      - name: payments
        image: ghcr.io/btjimerson/payments
        ports:
        - containerPort: 8080
        env:
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: payment-secret
              key: stripe-api-key
        - name: SPRING_PROFILES_ACTIVE
          value: yugabyte
        - name: YB_URL
          value: "jdbc:yugabytedb://yb-tserver-0.yb-nodes.svc.cluster.local:5433/yugabyte?sslmode=require"
        - name: YB_USER
          value: "yugabyte"
        - name: YB_PASSWORD
          value: "P@ssword11"
